### ISSUE TITLE
[Idea] Add topics to plugin

### ISSUE THREAD

**Issue by deku-m** [peterbaumert/netbox-device-view#10]
Suggestion:

To try to get more people to your plugin, maybe they also contribute. 
It might also help to add the topics to your plugin under description with the wheel.
![afbeelding](https://github.com/peterbaumert/netbox-device-view/assets/37069737/82199d6e-2362-4c98-a55d-15cc5ce9032f)

As i mostly use it to search for plugins using the topic netbox-plugins.

**Comment by peterbaumert** [comment]
done. ty for the hint :)
