### ISSUE TITLE
LC-Patchpanel example

### ISSUE THREAD

**Issue by deku-m** [peterbaumert/netbox-device-view#12]
I tried your example with the patchpanel LC.
Using the device-library "Generic LC 24-port Fiber Panel".
This is unfortunately missing the ports only 24 shows up.
![device-view-lc](https://github.com/peterbaumert/netbox-device-view/assets/37069737/b684d4bd-e802-44ec-8515-db9a6d026d15)

As you can see i have a lot of cable connection on the rear also on the front btw.
![device-lcports](https://github.com/peterbaumert/netbox-device-view/assets/37069737/591143cc-bcf5-40fa-9d59-22a4e606f7ac)

Also some design things in Edge:
- Mark X on the square not in center
- And the square is not in middle of the panel

**Comment by peterbaumert** [comment]
Did you alter the example to match your names?

Your rear ports are only names rear. So you have to rename rear-port-1 to port-1. same for your front ports.

**Comment by deku-m** [comment]
How stupid, thanks.
