### ISSUE TITLE
Support for only numbers as Port without Port in front.

### ISSUE THREAD

**Issue by deku-m** [peterbaumert/netbox-device-view#17]
THere are devices that use only numbers as Ports like in the device-library from netbox > sc-panels.
But there are also people that configure there ports like with floornumbers.
1001 1020 etc where 1xxx is the floor number.
So they dont use any Port in front of it.
<img width="543" alt="Scherm­afbeelding 2023-07-10 om 22 20 54" src="https://github.com/peterbaumert/netbox-device-view/assets/37069737/bdeb7844-98f2-4103-b33a-9f97671a61ea">

And there are also sub ports on some devices like 1.1 or 1.2.
<img width="441" alt="Scherm­afbeelding 2023-07-10 om 22 20 19" src="https://github.com/peterbaumert/netbox-device-view/assets/37069737/a4a913fd-0129-41f0-ad03-048774f92e58">

**Comment by peterbaumert** [comment]
Hi, yeah i have to rework the port "preparation" part.

**Comment by cybarox** [comment]
I have seen you use regex to match the interface name. 

You could use this one: `^(?P<type>([a-z]*))((?P<dev>[0-9]+).)?((?P<module>[0-9]+).)?((?P<port>[0-9]+))$` 
- `*` match zero or more characters in group type
- `.` match any delimiting characters between match groups e.g. `1.1` `eth0.10` `eno3p0`

Examples: [https://regex101.com/r/XM47Bk/1](https://regex101.com/r/XM47Bk/1)

Maybe you could get the Interface type via interface.type field which is a required field of the interface NetBox object. 

Nice project so far!

**Comment by peterbaumert** [comment]
can you try with v0.1.3 again @deku-m ?

**Comment by deku-m** [comment]
Hi @peterbaumert,

Tried with (SC-Panel) but for me its not working yet maybe i am doing something wrong?.
![afbeelding](https://github.com/peterbaumert/netbox-device-view/assets/37069737/eca2eef7-0570-48a9-ac64-200854625616)
![afbeelding](https://github.com/peterbaumert/netbox-device-view/assets/37069737/3c98c194-e4de-4766-b58d-21d05a058e55)
 
```
/* Ports are named "SC 1", "SC 2" | "Rear Port 1", "Rear Port 2" and so on */ .deviceview.area.dFront { /* both set to auto to overwrite the 32 columns 2 rows design */ grid-auto-rows: auto; grid-auto-columns: auto; grid-template-areas: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24" } 
.deviceview.area.dRear { /* both set to auto to overwrite the 32 columns 2 rows design */ grid-auto-rows: auto; grid-auto-columns: auto; grid-template-areas: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24" }
```
Using device-type:
https://github.com/netbox-community/devicetype-library/blob/master/device-types/Generic/SC-24-port-fiber-patch-panel.yaml

**Comment by peterbaumert** [comment]
Will have a look and get back to you

**Comment by peterbaumert** [comment]
Can you try with v0.1.4 and

```
/* Ports are named "1", "2" and so on for front and rear */
.deviceview.area.dFront {
	/* both set to auto to overwrite the 32 columns 2 rows design */
	grid-auto-rows: auto;
	grid-auto-columns: auto;
	grid-template-areas: "p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24";
}
.deviceview.area.dRear {
	/* both set to auto to overwrite the 32 columns 2 rows design */
	grid-auto-rows: auto;
	grid-auto-columns: auto;
	grid-template-areas: "p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24";
}
```

**Comment by deku-m** [comment]
> Seems like css grids dont like numeric only names :D
> 
> Can you try with v0.1.4 and
> 
> ```
> /* Ports are named "1", "2" and so on for front and rear */
> .deviceview.area.dFront {
> 	/* both set to auto to overwrite the 32 columns 2 rows design */
> 	grid-auto-rows: auto;
> 	grid-auto-columns: auto;
> 	grid-template-areas: "p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24";
> }
> .deviceview.area.dRear {
> 	/* both set to auto to overwrite the 32 columns 2 rows design */
> 	grid-auto-rows: auto;
> 	grid-auto-columns: auto;
> 	grid-template-areas: "p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24";
> }
> ```
This works !
