### ISSUE TITLE
Great start ! some more ideas

### ISSUE THREAD

**Issue by PieterL75** [peterbaumert/netbox-device-view#20]
I like this a lot !!!!

Some new things for upcoming releases :
- allow unlimited lines (we have chassis with ports on 4 different heights)
- combine 2 port as one (for ex QSFP are wider than SFP)
- combine 2x2 ports as one

**Comment by peterbaumert** [comment]
Hey thanks.

2 and 3 should be possible. The cisco 9500 example has the 100gig qsfp "wide" version.
If you want it 2x2 you just have to use same name in the second row of ports too.

'''
Gi24 qspf1 qsfp1
Gi25 qsfp1 qsfp1
'''

Something like this.

**Comment by PieterL75** [comment]
Also, the enforcement of that interface names to be `{interfacename}{module}-{port}` is not very handy
We have devices that are Ethernet1/1, 1/2, 1/3 and also Ethernet45/1, 46/1, 47/1
Storage arrays just use e0c, e0d, e0e etc

**Comment by peterbaumert** [comment]
> Also, the enforcement of that interface names to be `{interfacename}{module}-{port}` is not very handy
> 
> We have devices that are Ethernet1/1, 1/2, 1/3 and also Ethernet45/1, 46/1, 47/1
> 
> Storage arrays just use e0c, e0d, e0e etc

Yes this is already mentioned in one of the other issues and i will rework that part.

**Comment by peterbaumert** [comment]
can you try with v0.1.3 again @PieterL75  ?
