### ISSUE TITLE
Plugin description

### ISSUE THREAD

**Issue by deku-m** [peterbaumert/netbox-device-view#5]
Hi,

In the admin gui from netbox there is a part where the plugins are mentioned (installed_plugins).
All are listed there coming from the configuration.py under plugins ofcourse.

But i notice your description is almost everything from github i think.

See below:
![device-view](https://github.com/peterbaumert/netbox-device-view/assets/37069737/753c3426-c646-4587-85e6-b7bdb6fac2c2)

**Comment by peterbaumert** [comment]
Thx for noticing this. Its my first plugin so still learning. Will look into it.
