### ISSUE TITLE
Plugin configuration documentation.

### ISSUE THREAD

**Issue by deku-m** [peterbaumert/netbox-device-view#6]
Hi,

Doesnt your plugin documentation(readme) supposed to be adjusted to the following?
```
# In your configuration.py
PLUGINS = ["netbox-device-view"]
```
Should that be:
```
# In your configuration.py
PLUGINS = ["netbox_device_view"]
```

Aswell as:
`python3 manage.py migrate netbox-device-view`
to
`python3 manage.py migrate netbox_device_view`

**Comment by peterbaumert** [comment]
Uh yeah i guess. Will check again and update doc. Thank you
