### ISSUE TITLE
Error device view on ports.

### ISSUE THREAD

**Issue by deku-m** [peterbaumert/netbox-device-view#7]
Hi,

Sorry to add so many issues etc. And thank you for the plugin
But i was testing the plugin and i am having a issue.

Probaly i am doing something wrong.

The following is happening:
When creating the device view which you created as a example i just copy paste it:
![device-view-input-1](https://github.com/peterbaumert/netbox-device-view/assets/37069737/95c3cf16-b71e-41f9-9811-59bf3d919b02)
After going to the device type with the devices:
![device-view-types-1](https://github.com/peterbaumert/netbox-device-view/assets/37069737/bd2e7acd-8291-43e9-97ea-22f43e53f1ef)
Selecting a device i get a error saying:
![deviceviewerror-1](https://github.com/peterbaumert/netbox-device-view/assets/37069737/d5921037-549f-4ab5-bf48-977486e181a0)
WHile doing the pip install and migrate/static everything is fine.

You know what is going wrong?
Is the example supposed to use the same interface names as listed in the devices itself??

**Comment by peterbaumert** [comment]
will fix soon. somehow fu** up :D

you dont need to appologize for opening issues, at least someone uses my plugin :)

**Comment by peterbaumert** [comment]
Can you install latest version and test again?
